lane_detector: 
  {
    threshold_c: -55,
    real_window_size: 0.1,

    pf_num_points: 3,
    pf_num_samples: 50,
    pf_num_samples_vis: 4,
    pf_std_min: 0.01,
    pf_std_max: 0.03,
    obstacle_window_size: 0.09,
    obstacles_threshold: 180,

    max_mid_line_distance: 0.12,
    max_mid_line_gap: 0.25
  }
