image: registry.gitlab.com/knr-selfie/carolocup/carolocup:latest

variables:
  GLOBAL_C11: "true"
  GIT_SUBMODULE_STRATEGY: recursive

catkin_make:
  stage: build
  script:
    - catkin_make
  only:
    - develop
    - master

catkin_make roslint:
  stage: test
  script:
    - catkin_make roslint -DROSLINT_CPP_OPTS="--filter=-whitespace/braces,-runtime/references"
  only:
    - develop
    - master
    - merge_requests

catkin lint:
  stage: test
  script:
    - catkin_lint --strict --ignore env_var .
  only:
    - develop
    - master
    - merge_requests

Code formatting check:
  stage: test
  script:
    - echo "Checking formatting of python code in cane of fail you can format it using yapf (command yapf -i -r ./)"
    - yapf -q --recursive ./
    - echo "Checking formatting of C++ code in case of fail you can format it using clang-format"
    - wget https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py
    - python3 run-clang-format.py -r src
  only:
    - merge_requests