image: registry.gitlab.com/knr-selfie/carolocup/carolocup:latest

variables:
  GLOBAL_C11: "true"
  GIT_SUBMODULE_STRATEGY: recursive

catkin_make:
  stage: build
  script:
    - catkin_make
  only:
    - develop
    - master

catkin_make roslint:
  stage: test
  script:
    - catkin_make roslint
  only:
    - develop
    - master
    - merge_requests

catkin lint:
  stage: test
  script:
    - catkin_lint --strict --ignore env_var .
  only:
    - develop
    - master
    - merge_requests
