image: ros:noetic-robot

variables:
  ROS_PACKAGES_TO_INSTALL: ""
  GLOBAL_C11: "true"

cache:
  paths:
    - ccache/

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git >/dev/null
    ######################### INSTALL PYLON SDK #########################
  - apt install -y wget >/dev/null
  - wget "https://www.baslerweb.com/fp-1551786516/media/downloads/software/pylon_software/pylon-5.2.0.13457-x86_64.tar.gz" >/dev/null
  - tar xvzf pylon-5.2.0.13457-x86_64.tar.gz >/dev/null
  - cd pylon-5.2.0.13457-x86_64
  - tar -C /opt -xzf pylonSDK*.tar.gz >/dev/null
  - cd ..
  - rm -r pylon-5.2.0.13457-x86_64
  - rm pylon-5.2.0.13457-x86_64.tar.gz
  - sudo sh -c 'echo "yaml https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.yaml " > /etc/ros/rosdep/sources.list.d/15-plyon_camera.list'
  - rosdep update
    ######################### INSTALL PYLON SDK #########################
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

catkin_make:
  stage: build
  script:
    - catkin_make

catkin_make roslint:
  stage: test
  script:
    - catkin_make roslint

catkin lint:
  stage: test
  image: ros:noetic-robot
  before_script:
      ######################### INSTALL PYLON SDK #########################
    - apt update >/dev/null 2>&1 && apt install -y wget >/dev/null
    - wget "https://www.baslerweb.com/fp-1551786516/media/downloads/software/pylon_software/pylon-5.2.0.13457-x86_64.tar.gz" >/dev/null
    - tar xvzf pylon-5.2.0.13457-x86_64.tar.gz >/dev/null
    - cd pylon-5.2.0.13457-x86_64
    - tar -C /opt -xzf pylonSDK*.tar.gz >/dev/null
    - cd ..
    - rm -r pylon-5.2.0.13457-x86_64
    - rm pylon-5.2.0.13457-x86_64.tar.gz
    - sudo sh -c 'echo "yaml https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.yaml " > /etc/ros/rosdep/sources.list.d/15-plyon_camera.list'
    - rosdep update
      ######################### INSTALL PYLON SDK #########################
    - apt install -y python3-catkin-lint >/dev/null 2>&1
  script:
    - catkin_lint --strict --ignore missing_install_target --ignore env_var .
