stm32_bridge:
  {
    
  }

pylon_camera_node: 
  {
    camera_info_url: "",
    image_encoding: "mono8",
    frame_rate: 150,
    brightness: 150,
    brightness_continuous: true,
    exposure_auto: false,
    gain_auto: true,
    exposure: 6000.0,
    height: 400,
    width: 1024,
    roi_offset_x: 512,
    roi_offset_y: 460
  }