lane_detector: 
  {
    threshold_c: -45,
    real_window_size: 0.1,

    pf_num_points: 3,
    pf_num_samples: 40,
    pf_num_samples_vis: 4,
    pf_std_min: 0.01,
    pf_std_max: 0.03,
    obstacle_window_size: 0.09,
    obstacles_threshold: 180,

    max_mid_line_distance: 0.12,
    max_mid_line_gap: 0.25
  }

obstacle_detector: 
  {
    max_range: 2.0,
    min_range: 0.03,
    obstacles_frame: "laser",
    visualization_frame: "base_link",
    output_frame: "base_link",
    lidar_offset: 0.0,
    segment_threshold: 0.03,
    max_segment_size: 0.5,
    min_segment_size: 0.04,
    min_to_divide: 0.03,
    upside_down: false

  }

odometry: 
  {
    rear_axis_handle: "base_link",
    spin_rate: 10
  }
