diagnostics:
  {
    0_sensor_datatype: "LaserScan",
    0_sensor_directory: "/dev/sensors/hokuyo_H1312790",
    0_sensor_hz: 100,
    0_sensor_name: "Lidar",
    0_sensor_topic: "/scan",
    1_sensor_datatype: "Image",
    1_sensor_hz: 102,
    1_sensor_name: "Camera",
    1_sensor_topic: "camera_basler/image_rect",
    frequency: 2,
    debug: false,
    delay: 10
  }
