#!/usr/bin/env python3

import actionlib
import rospy
from std_msgs.msg import String
from custom_msgs.msg import parkGoal

from crosswalk import talker

if __name__ == '__main__':
    rospy.loginfo("Started")
    try:
        talker()
    except rospy.ROSInterruptException:
        pass