#!/usr/bin/env python3

import actionlib
import rospy
from std_msgs.msg import String
from custom_msgs.msg import parkGoal

from crosswalk import CrosswalkManager

if __name__ == '__main__':
    rospy.init_node('crosswalk_node')
    rospy.loginfo("Started")
    manager = CrosswalkManager()
    try:
        manager.start()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
