#!/usr/bin/env python

import sys

from rqt_selfie_base.base_module import CarStatusPlugin
from rqt_gui.main import Main

plugin = 'rqt_selfie_base'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))