stm32_bridge:
  {
    ackermann_offset_front: 0.0,
    ackermann_offset_back: 0.0,
    parallel_offset_front_right: 0.1,
    parallel_offset_back_right: 0.0,
    parallel_offset_front_left: 0.0,
    parallel_offset_back_left: -0.25,
    front_axis_offset: 0.0,
    back_axis_offset: 0.0
  }
