const_setpoint:
  {
    topic: "setpoint",
    value: 0,
    publish_rate: 2
  }

control_calculator:
  {
    L: 0.3,
    look_ahead: 0.3,
    publish_rate: 50,
    max_acceleration: 5.0,
    max_curvature: 1.8,
    min_speed: 0.2
  }

pid_controller: 
  {
    Kd: 0.12,
    Ki: 0.0,
    Kp: 1.0,
    lower_limit: -0.785,
    upper_limit: 0.785,
    windup_limit: 10
  }

pid_tuner:
  {
    L_Kp: 1.0,
    L_Ki: 0,
    L_Kd: 0.12,

    M_Kp: 1.0,
    M_Ki: 0,
    M_Kd: 0.12,

    H_Kp: 1.0,
    H_Ki: 0,
    H_Kd: 0.12,

    M_speed: 0.5,
    H_speed: 1.0,

    speed_change_treshold: 0.1
  }

cmd_creator:
  {
    publish_rate: 80
  }

drive_multiplexer:
  {

  }

stm32_bridge:
  {
    
  }

pylon_camera_node: 
  {
    camera_info_url: "",
    image_encoding: "mono8",
    frame_rate: 150,
    brightness: 150,
    brightness_continuous: true,
    exposure_auto: false,
    gain_auto: true,
    exposure: 6000.0,
    height: 400,
    width: 1024,
    roi_offset_x: 512,
    roi_offset_y: 460
  }

lane_pilot:
  {
    right_lane_offset: -0.2,
    left_lane_offset: 0.2,

    ackermann_mode: true,

    maximum_speed: 1.0,
    slowdown_speed: 0.8,
    lane_change_speed: 0.5,
    lane_change_distance: 0.6,
    max_length_of_obstacle: 0.4,
    max_distance_to_obstacle: 1.2,
    safety_margin: 1.0,
    pos_tolerance: 0.01,
    num_proof_to_slowdown: 2,
    num_corners_to_detect: 2,

    ROI_min_x: 0.5,
    ROI_max_x: 1.7,
    ROI_min_y: -1.0,
    ROI_max_y: 1.0,

    right_obst_area_min_x: 0.3,
    right_obst_area_max_x: 1.6,
    right_obst_area_min_y: -0.85,
    right_obst_area_max_y: 0.15,
  }

path_generator:
  {
    max_distance: 1.5,
    interval_x: 0.1
  }

lane_detector: 
  {
    threshold_c: -45,
    real_window_size: 0.1,

    pf_num_points: 3,
    pf_num_samples: 40,
    pf_num_samples_vis: 4,
    pf_std_min: 0.01,
    pf_std_max: 0.03,
    obstacle_window_size: 0.09,
    obstacles_threshold: 180,

    max_mid_line_distance: 0.12,
    max_mid_line_gap: 0.25
  }

obstacle_detector: 
  {
    max_range: 2.0,
    min_range: 0.03,
    obstacles_frame: "laser",
    visualization_frame: "base_link",
    output_frame: "base_link",
    lidar_offset: 0.0,
    segment_threshold: 0.03,
    max_segment_size: 0.5,
    min_segment_size: 0.04,
    min_to_divide: 0.03,
    upside_down: false

  }

odometry: 
  {
    rear_axis_handle: "base_link",
    spin_rate: 10
  }

free_drive: 
  {
    max_speed: 1.0,
    starting_line_distance_to_end: 0.65,
    intersection_distance_to_end: 1.3,
    distance_to_verify_event_: 1.0
  }

intersection_server: 
  {
    distance_to_intersection: 0.75,
    road_width: 1.05,
    point_min_y: -0.5,
    point_max_y: 0.7,
    stop_time: 3,
    speed_default: 1.0,
    num_corners_to_detect: 1,
    distance_of_blind_approaching: 0.2,
  }

park: 
  {

    idle_time: 2.0,
    max_turn: 0.5,
    back_to_mid: 0.18,
    parking_speed: 0.8,
    start_parking_speed: 0.8,
    iter_distance: 0.2,
    angle_coeff: 0.5,
    turn_delay: 0.1,
    line_dist_end: 0.15
  }

parking_spot_detector: 
  {
    default_speed_in_parking_zone: 0.8,
    max_distance_to_free_place: 0.4,
    speed_when_found_place: 0.6,
    length_of_parking_area: 5.5,

    ROI_max_x: 2,
    ROI_max_y: 0.2,
    ROI_min_x: 0.01,
    ROI_min_y: -0.6
  }

scheduler: 
  {
    begin_action: 1,
    parking_spot: 0.63,
    parking_steering_mode: 1, # 0 - ackermann 1 - paralell
    drive_steering_mode: 2, # 0 - ackermann  1 - paralell 2 - front axis only 
    starting_distance: 5.0
  }

starting_procedure: 
  {
    starting_speed: 2.0,
    use_scan: false,
    use_qr: false,
    Kp: 1.0
  }
qr_decoder:
  {
    min_detect_rate: 0.4,
    iterations_to_valid: 2,
  }
gate_scanner:
  {
    no_obstacle_time_thresh: 1.5,
    min_distance: 0.1,
    max_distance: 0.5,
    min_width: 0.2,
    min_gate_seen_count: 5
  }

